version: '3.0'
services: 
    api:
      image: node:16.3.0
      command: npm run start
      depends_on:
        - postgres
      ports:
        - 3000:3000
      volumes:
        - ./:/app
      working_dir:  /app
      
      links:
        - postgres

    postgres:
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: lreddit
      ports:
        - 5432:5432
      volumes:
        - pgdata:/data/postgres
volumes:
    pgdata:
      driver: local